package com.sankatmochan.mesh.stt

import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.abs

/**
 * The mel parity gate: MelFrontend (Kotlin) must reproduce the NeMo preprocessor's features, or
 * IndicConformer sees a different distribution than it trained on and accuracy collapses.
 *
 * Golden vectors are generated by backend/scripts/dump_mel_golden.py (Python reconstruction matched
 * the scripted preprocessor to ~8e-5). This runs the SAME clip through MelFrontend on-device and
 * asserts they agree. Run on the OnePlus 15:  ./gradlew connectedDebugAndroidTest
 */
@RunWith(AndroidJUnit4::class)
class MelParityTest {

    @Test
    fun matchesPythonGolden() {
        val appCtx = InstrumentationRegistry.getInstrumentation().targetContext
        val testCtx = InstrumentationRegistry.getInstrumentation().context

        val meta = testCtx.assets.open("mel_golden/meta.txt").use { it.readBytes().decodeToString() }
        val t = Regex("T=(\\d+)").find(meta)!!.groupValues[1].toInt()
        val pcm = readF32(testCtx, "mel_golden/pcm.f32")
        val golden = readF32(testCtx, "mel_golden/mel.f32")   // (80 * T) row-major

        val mel = MelFrontend.fromAssets(appCtx)              // real window512 + filterbank assets
        val feats = mel.logMel(pcm)

        assertTrue("validFrames ${feats.validFrames} != golden T $t", feats.validFrames == t)

        var maxDiff = 0.0
        for (m in 0 until MelFrontend.NMEL) {
            for (col in 0 until t) {
                val got = feats.data[m * MelFrontend.MAX_FRAMES + col]
                val exp = golden[m * t + col]
                maxDiff = maxOf(maxDiff, abs(got - exp).toDouble())
            }
        }
        assertTrue("mel max-abs-diff $maxDiff exceeds 1e-2 - features drifted from NeMo", maxDiff < 1e-2)
    }

    private fun readF32(ctx: android.content.Context, asset: String): FloatArray {
        val bytes = ctx.assets.open(asset).use { it.readBytes() }
        val bb = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN)
        return FloatArray(bytes.size / 4) { bb.float }
    }
}
